pull_request_rules:
  - name: Ping PR author when conflicting and add label
    conditions:
      - conflict
      - -closed
    actions:
      comment:
        message: >
          👋 {{author}}, your PR is conflicting and needs to be updated to be merged
      label:
        toggle:
          - conflict
