name: Prek

on:
  merge_group:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  prek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.3

      - uses: cachix/install-nix-action@v31.10.7
        with:
          extra_nix_config: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v17
        with:
          name: spikonado
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build and Cache Shell Environment
        run: |
          nix develop --profile spikonado.com-shell -c true
          cachix push spikonado spikonado.com-shell

      - name: Install Bun dependencies
        shell: 'nix develop --profile spikonado.com-shell -c bash -e {0}'
        run: bun install --frozen-lockfile

      - name: Run prek
        shell: 'nix develop --profile spikonado.com-shell -c bash -e {0}'
        run: prek run -a
